---
title: "Client Report - Project 0: Introduction"
subtitle: "Course DS 250"
author: "David Lunceford"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

```{python}
import pandas as pd
import numpy as np
from lets_plot import *

LetsPlot.setup_html(isolated_frame=True)
```


```{python}
# Learn morea about Code Cells: https://quarto.org/docs/reference/cells/cells-jupyter.html

# Include and execute your code here
from palmerpenguins import load_penguins
df = load_penguins()
```

## QUESTION|TASK 1

__Include the tables created from [PY4DS: CH2 Data Visualization](https://aeturrell.github.io/python4DS/data-visualise.html) used to create the above chart (Hint: copy the code from 2.2.1. The penguins data frame and paste each in the cells below)__


```{python}

penguins = load_penguins()
penguins

```

_include figures in chunks and discuss your findings in the figure._

```{python}
# Include and execute your code here

penguins.head()

```


## QUESTION|TASK 2

__Recreate the example charts from [PY4DS: CH2 Data Visualization](https://aeturrell.github.io/python4DS/data-visualise.html) of the textbook. (Hint: copy the chart code from 2.2.3. Creating a Plot, one for each cell below)__


```{python}
# Include and execute your code here

(
    ggplot(data=penguins, mapping=aes(x="flipper_length_mm", y="body_mass_g"))
    + geom_point()
)

```

This is a scatter plot that visualizes the relationship between a study sample of penguins' flipper length in millimeters and body mass. Generally we see that as the flipper length increases so does the body mass.

```{python}
# Include and execute your code here

(
    ggplot(
        data=penguins,
        mapping=aes(x="flipper_length_mm", y="body_mass_g", color="species"),
    )
    + geom_point()
)

```

In this scatter plot we have specified the individual species included in the study with the legend on the right, and separated the species by color. We see that the Gentoo penguins are generally the largest with the highest body mass and longest flippers. 


```{python}
# Include and execute your code here

(
    ggplot(
        data=penguins,
        mapping=aes(x="flipper_length_mm", y="body_mass_g", color="species"),
    )
    + geom_point()
    + geom_smooth(method="lm")
)

```

In this plot we have added a line of best fit that maps the progression of values using a linear model. The species each have their own line of best fit, with the species legend indicating which line corresponds to which species. 

```{python}
# Include and execute your code here

(
    ggplot(data=penguins, mapping=aes(x="flipper_length_mm", y="body_mass_g"))
    + geom_point(mapping=aes(color="species"))
    + geom_smooth(method="lm")
)

```

In this chart we have combined the three lines of best fit into one linear regression that corresponds to the progression of values of all three species together. 


```{python}
# Include and execute your code here

(
    ggplot(data=penguins, mapping=aes(x="flipper_length_mm", y="body_mass_g"))
    + geom_point(aes(color="species", shape="species"))
    + geom_smooth(method="lm")
    + labs(
        title="Body mass and flipper length",
        subtitle="Dimensions for Adelie, Chinstrap, and Gentoo Penguins",
        x="Flipper length (mm)",
        y="Body mass (g)",
        color="Species",
        shape="Species",
    )
)

```

In this final chart we have separated the points corresponding to each species by shape, included the line of best fit from the previous chart. We've cleaned up the axis titles, species legend, and added the title for the overall visualization of the data. 
